# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    working_directory: ~/erenard/mandelbrot
    parallelism: 1
    environment:
      CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
      CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
    docker:
      - image: circleci/node:8-browsers
    branches:
      only:
        - master
    steps:
      - checkout
      - run: mkdir -p $CIRCLE_ARTIFACTS $CIRCLE_TEST_REPORTS
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      # - run: if [ -z "${NODE_ENV:-}" ]; then export NODE_ENV=test; fi
      - run: export PATH="~/erenard/mandelbrot/node_modules/.bin:$PATH"
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm run build
      - run: git config --global -l #<= totally unnecessary, but "fixes" problem?
      - run: git config --global user.email circleci@circleci
      - run: git config --global user.name CircleCI
      - add_ssh_keys:
          fingerprints:
            - "24:42:97:78:93:47:a7:c1:2b:62:7a:27:e6:23:7d:73"
      - run: npm run deploy
